core: improved error handling
This commit reworks the error handling from:

- recovering panics to logs for runtime errors
- pretty printing errors found while lexing
- simply logging errors found while parsing

To pretty and well formatted errors with context and enough information
to actually fix the issue. The following errors display the previous
error handling vs the new error handling:

    $ sophia -exp "(put =)"
    15:08:25.818095 err: Unknown token '=' at [l 1:5]

    001 |	(put =)
                ^

    15:08:25.818162 lexer error

    $ sophia -exp "(put =)"
    error: Unknown character

            at: cli:1:6:

               1| (put =)
                |      ^

    Unexpected "="
    Syntax errors found, skipping remaining interpreter stages. (parsing and evaluation)
    exit status 1

Runtime errors were previously handled by panic and printing the
recovered error:

    $ sophia test.phia
    15:10:20.118010 err: variable 'name' is not defined!
    15:10:20.118056 runtime error
    15:10:20.118062 error in source file 'test.phia' detected, stopping...

    $ sophia test.phia
    error: Undefined variable

            at: /home/teo/programming/Sophia/test.phia:4:6:

               2| (let neme "anon")
               3| ;; printing undefined variable
               4| (put name)
                |      ^^^^

    Variable "name" is not defined.

Empty files are now including more context

    $ sophia empty.phia
    15:12:47.180062 err: input is empty, stopping
    15:12:47.180125 lexer error

    $ sophia empty.phia
    error: Unexpected end of file

	at: /home/teo/programming/Sophia/test.phia:1:1:

	   1|
	    | ^

    Source possibly empty
    Syntax errors found, skipping remaining interpreter stages. (parsing and evaluation)
    exit status 1

Change list:
- core/token: new Token.LinePos field for error display
- core/serror: new package for pretty printing errors with
  context, api inspired by 'log'
    - contains a default formatter, needs to be set before usage via
      'serror.SetDefault'
    - costly error computation occurs on calling 'serror.Display'
- reworked tests to use 'serror.SetDefault', 'serror.NewFormatter' and
  'serror.HasErrors'
- core: reworked lexer, parser and runtime errors to not panic or log and
  instead call 'serror.Add'.
- core/lexer: fixed a bug when encountering a new line prompted '*Lexer.Lex()' to
  increment '*Lexer.linepos' twice
- core: improved error messages across the code base, but especially for
  parser and runtime errors
    - more context (2 lines before and 2 lines after the offending line)
    - detailed error titles and descriptions
    - highlighting line and position the error occurred at
- core/expr: runtime type errors improvements:
    - correct types displayed (no interface{} anymore)
    - correct tokens and token types passed to the function
- core/lexer: fixed bug that caused incorrect 'linepos' and
  'pos' values
- core/lexer: switched from []byte to string input
- core/lexer: switched internal source stream type from []byte to []rune,
  resulting in the lexer supporting utf-8 encoded source files
- core: removed 'hasError' from '*Lexer' and '*Parser', both replaced with
  'serror.HasErrors'
- core/parser: '*Parser.Parse()' now returns the parsed ast when encountering a nil
  result from '*Parser.parseStatment()'
- core/parser: improved error messages and handling for the 'load' keyword
- core/parser: '*Parser.parseStatment()' returns if the recursive call results in nil
- core/parser: added error handling for the 'eq' keyword
- core/run: include new prompt: 'sophia> '
- core/run: switch from []byte to string func signature
- core/run: in depth error reporting for interpreter stages
- core/run: panic recovery calls 'serror.Display'
- core/run: new flag '-all-errors'